<?php
/**
 * Implements hook_init().
 *
 * Funs on every page.
 */
function demo_permission() {
  return array(
    'administer demo module' => array(
      'title' => t('Administer Demo Module'),
      'description' => t('Perform administration tasks for demo mod'),
    ),
  );
}

function demo_node_view($node, $view_mode, $langcode) {
  $node->content['demo_field'] = array(
    '#type' => 'markup',
    '#markup' => '<p>'. t('This is only a demo') . '</p>',
    '#weight' => -10,
  );
  $node->content['demo_list'] = array(
    '#items' => array('green', 'blue', 'yellow', 'red'),
    '#theme' => 'item_list',
    '#weight' => -9,
  );
  //dpm($node);
}

function demo_block_info() {
  $blocks = array();

  $blocks['departments'] = array(
    'info' => t('City Departments'),
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
  );

  return $blocks;
}

function demo_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case 'departments':
      $block['subject'] = t('City Departments');
      $block['content'] = array(
        '#type' => 'markup',
        '#markup' => _depts_list(),
      );
    break;
  }

  return $block;
}

function _depts_list() {
  
  $tax_name_sql = db_query('SELECT tid as tid, vid as vid, name as name FROM `taxonomy_term_data` WHERE vid = :vid', array(':vid' => 2));
  if (!empty($tax_name_sql)) {
    foreach ($tax_name_sql as $term) {
      //$items[] = ("<li><a href='taxonomy/term/" . $term->tid . "'>" . $term->name . "</a></li>");
      $depts .= ("<li><a href='taxonomy/term/" . $term->tid . "'>" . $term->name . "</a></li>");
    }
  }
  return $depts;
}
